### ISSUE TITLE
Reserva de refeições on-line pelos clientes

### ISSUE THREAD

**Issue by andrepenteado** [projetoleaf/ru#13]
Disponibilizar que os clientes possam fazer a reserva das refeições via internet. O período para solicitar as reservas é toda segunda das 7h30 as 10h. E os dias disponíveis são os dias do cardápio da semana seguinte.

**Comment by thiagopiovan** [comment]
https://github.com/projetoleaf/ru/blob/master/docs/script.txt

*Vamos discutir amanhã com a Juliana a cerca do banco.

**Comment by thiagopiovan** [comment]
@giovanacarolini terminou essa funcionalidade
