### ISSUE TITLE
Efetivar compra após pagamento da refeição

### ISSUE THREAD

**Issue by andrepenteado** [projetoleaf/ru#14]
Após a solicitação das reservas, o cliente efetua o pagamento junto a seção de finanças e efetiva a compra da refeição.

**Comment by thiagopiovan** [comment]
Isso será feito atualizando-se o status da refeição na tabela reserva_item. Passará de (aguardando o pagamento) para (pago) e assim será aceito pela catraca.

*Não é registrado no banco as mudanças no status da refeição, por enquanto não se verificou necessário alterar o banco para isso. O status dirá se a refeição foi paga, expirada(não paga), transferida(não pode ser transferida de novo), transferente ou aguardando pagamento. Sendo possível através do status gerar relatórios diversos mesmo sem registros de histórico.

*Não esquecer de bloquear transferência para si mesmo (validação).

**Comment by thiagopiovan** [comment]
@giovanacarolini terminou essa funcionalidade
