### ISSUE TITLE
Dúvida: inserir imagens

### ISSUE THREAD

**Issue by victorscatena** [projetoleaf/ru#2]
Gostaria de saber como colocar imagens em uma nova página. Estou tentando de várias maneiras mas nenhuma funciona @andrepenteado

**Comment by andrepenteado** [comment]
Como está tentando? Coloque um pedaço do código pra eu poder entender melhor o que precisa.

**Comment by victorscatena** [comment]
Criei uma pasta imagens dentro da pasta resources e estou tentando as seguintes linhas de código:

img th:src="@{/imagens/test.png}"/>
img th:src="@{/resources/imagens/test.png}" />
img src="/resources/imagnes/test.png" />
